version: '3'
services:
  localstack:
    image: "localstack/localstack"
    environment:
      - SERVICES=sqs
      - PORT_WEB_UI=8000
    ports:
      - "4576:4576"
      - "8000:8000"
  redis:
    image: "redis:alpine"
  # web:
  #   build: .
  #     ports:
  #     - "8080:8080"